import fs from 'fs';
import path from 'path';
import ngrok from '@ngrok/ngrok';
import { logger } from './logger.js';

const MOBILE_ENV_PATH = path.resolve(process.cwd(), '../narang-mobile/.env.local');

export async function startNgrokTunnel(port) {
  const authtoken = process.env.NGROK_AUTHTOKEN;
  if (!authtoken) {
    logger.warn(
      'ENABLE_NGROK is set but NGROK_AUTHTOKEN is missing. Create a free token at https://dashboard.ngrok.com/get-started/your-authtoken'
    );
    return null;
  }

  try {
    const listener = await ngrok.forward({
      addr: Number(port),
      authtoken,
    });
    return listener.url()?.replace(/\/$/, '') ?? null;
  } catch (err) {
    logger.error(`ngrok tunnel failed: ${err.message}`);
    return null;
  }
}

/** Writes ngrok URL so Expo picks it up (overrides narang-mobile/.env). */
export function syncMobileEnv(publicUrl) {
  const content = [
    '# Auto-generated by backend (npm run dev:tunnel) — do not commit',
    `EXPO_PUBLIC_API_URL=${publicUrl}`,
    '',
  ].join('\n');

  fs.writeFileSync(MOBILE_ENV_PATH, content, 'utf8');
  logger.info(`Mobile API URL → ${publicUrl}`);
  logger.info(`Updated ${MOBILE_ENV_PATH}`);
  logger.info('Restart Expo: cd narang-mobile && npx expo start --tunnel --clear');
}
